version: "3"
services:
  mysql:
    image: mysql
    container_name: lawSearch_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: Asia/Seoul
    restart: always

  backend:
    image: chanhee01/law-search
    container_name: lawSearch_backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET : LawSearch
      MYSQL_URL: $MYSQL_URL
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  lawSearch-redis:
    image: redis
    container_name: lawSearch_redis
    ports:
      - "6379:6379"
    volumes:
        - ./redis/data:/data
        - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always