spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      show-sql : true
      hibernate.format_sql : true
      dialect : org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      jdbc:
        time-zone: Asia/Seoul

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          required: true
          enable: true

jwt_secret : ${JWT_SECRET}