name: Deploy LawSearch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Modify application.yml
        run: |
          sed -i 's~url: ${MYSQL_URL}~url: '"${{ secrets.MYSQL_URL }}"'~' src/main/resources/application.yml
          sed -i 's~username: ${MYSQL_USER}~username: '"${{ secrets.MYSQL_USER }}"'~' src/main/resources/application.yml
          sed -i 's~password: ${MYSQL_PASSWORD}~password: '"${{ secrets.MYSQL_PASSWORD }}"'~' src/main/resources/application.yml
          sed -i 's~jwt_secret : ${JWT_SECRET}~jwt_secret : '"${{ secrets.JWT_SECRET }}"'~' src/main/resources/application.yml
          sed -i 's~username: ${EMAIL_USERNAME}~username: '"${{ secrets.EMAIL_USERNAME }}"'~' src/main/resources/application.yml
          sed -i 's~password: ${EMAIL_PASSWORD}~password: '"${{ secrets.EMAIL_PASSWORD }}"'~' src/main/resources/application.yml
          sed -i 's~gpt_url: ${GPT_URL}~gpt_url: '"${{ secrets.GPT_URL }}"'~' src/main/resources/application.yml
          sed -i 's~MYSQL_URL:.*~MYSQL_URL: '"${{ secrets.MYSQL_URL }}"'~' docker-compose.yml
          sed -i 's~MYSQL_USER:.*~MYSQL_USER: '"${{ secrets.MYSQL_USER }}"'~' docker-compose.yml
          sed -i 's~MYSQL_PASSWORD:.*~MYSQL_PASSWORD: '"${{ secrets.MYSQL_PASSWORD }}"'~' docker-compose.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: docker build -t chanhee01/law-search ./

      - run: docker push chanhee01/law-search

      - name: Generate deployment package
        run: zip -r deploy.zip Dockerfile docker-compose.yml build/libs/*.jar

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: lawSearch
          environment_name: LawSearch-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-767397959595
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip